# Generated by Django 6.0.2 on 2026-02-23 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_attendance_semester_studentresult_semester_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regulation',
            name='description',
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='semester',
            field=models.CharField(choices=[('1', '1-1'), ('2', '1-2'), ('3', '2-1'), ('4', '2-2'), ('5', '3-1'), ('6', '3-2'), ('7', '4-1'), ('8', '4-2')], max_length=1),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1-1'), ('2', '1-2'), ('3', '2-1'), ('4', '2-2'), ('5', '3-1'), ('6', '3-2'), ('7', '4-1'), ('8', '4-2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1-1'), ('2', '1-2'), ('3', '2-1'), ('4', '2-2'), ('5', '3-1'), ('6', '3-2'), ('7', '4-1'), ('8', '4-2')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1-1'), ('2', '1-2'), ('3', '2-1'), ('4', '2-2'), ('5', '3-1'), ('6', '3-2'), ('7', '4-1'), ('8', '4-2')], max_length=1, null=True),
        ),
    ]
