# Generated by Django 6.0.2 on 2026-02-23 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_regulation_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsubmission',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
