# Generated by Django 3.1.1 on 2026-03-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_auto_20260228_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='max_marks',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1-1'), ('2', '1-2'), ('3', '2-1'), ('4', '2-2'), ('5', '3-1'), ('6', '3-2'), ('7', '4-1'), ('8', '4-2')], max_length=1, null=True),
        ),
    ]
