# Generated by Django 3.1.1 on 2026-03-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20260301_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='show_in_marks',
            field=models.BooleanField(default=True),
        ),
    ]
