# Generated by Django 3.1.1 on 2026-03-01 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_subject_show_in_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.regulation'),
        ),
    ]
