# Generated by Django 3.1.1 on 2026-03-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_auto_20260301_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='external_marks',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='credits',
            field=models.FloatField(default=0),
        ),
    ]
