# Generated by Django 3.1.1 on 2026-03-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_auto_20260301_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='internal_marks',
            field=models.FloatField(default=0),
        ),
    ]
