# Generated by Django 3.1.1 on 2026-03-03 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_studymaterial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='regulation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.regulation'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.course'),
        ),
        migrations.AddField(
            model_name='regulation',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1-1'), ('2', '1-2'), ('3', '2-1'), ('4', '2-2'), ('5', '3-1'), ('6', '3-2'), ('7', '4-1'), ('8', '4-2')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='regulation',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.session'),
        ),
    ]
