# Generated by Django 3.1.1 on 2026-03-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_auto_20260303_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='semester',
            field=models.CharField(blank=True, choices=[('1', '1-1'), ('2', '1-2'), ('3', '2-1'), ('4', '2-2'), ('5', '3-1'), ('6', '3-2'), ('7', '4-1'), ('8', '4-2')], max_length=1, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('course', 'section', 'day', 'period', 'semester')},
        ),
    ]
