# Generated by Django 3.1.1 on 2026-03-03 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20260303_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCloudFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='student_cloud/')),
                ('category', models.CharField(choices=[('notes', 'Notes'), ('pdf', 'PDF'), ('question_paper', 'Question Paper'), ('important', 'Important File')], default='notes', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.student')),
            ],
        ),
    ]
