# Generated by Django 6.0.2 on 2026-03-11 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_staff_date_of_birth_staff_date_of_joining_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('mid1', 'I Mid-term Examinations'), ('mid2', 'II Mid-term Examinations'), ('lab_exam', 'Preparation & End Laboratory Examinations'), ('end_exam', 'End Theory Examinations'), ('workshop', 'Branch Specific Workshop'), ('results', 'Declaration of Results'), ('internship', 'Industry Internship'), ('next_commencement', 'Commencement of Next Semester'), ('other', 'Other')], max_length=20)),
                ('custom_name', models.CharField(blank=True, help_text='Used when event type is "Other"', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('duration_text', models.CharField(blank=True, help_text='e.g. "03 Days", "02 Weeks"', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='main_app.academiccalendar')),
            ],
            options={
                'ordering': ['order', 'start_date'],
            },
        ),
    ]
