# Generated by Django 3.1.1 on 2026-03-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0035_auto_20260312_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
    ]
