# Generated by Django 3.1.1 on 2026-04-04 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0038_auto_20260401_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
