# Generated by Django 3.1.1 on 2026-04-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0039_announcement_expires_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='academiccalendar',
            unique_together={('session', 'semester', 'regulation')},
        ),
    ]
