# Generated by Django 3.1.1 on 2026-04-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0040_auto_20260408_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academiccalendar',
            name='commencement_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='academiccalendar',
            name='instruction_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
