# Generated by Django 3.1.1 on 2026-04-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0041_auto_20260408_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
