# Generated by Django 3.1.1 on 2026-04-10 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0043_auto_20260410_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='short_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
