# Generated by Django 3.1.1 on 2026-04-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0044_subject_short_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='staff_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
