# Generated by Django 3.1.1 on 2026-04-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0045_staff_staff_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='show_in_attendance',
            field=models.BooleanField(default=True, help_text='Track attendance for this subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='show_in_results',
            field=models.BooleanField(default=True, help_text='Show results/grades for this subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='show_in_marks',
            field=models.BooleanField(default=True, help_text='Show in marks memo'),
        ),
    ]
