# Generated by Django 3.1.1 on 2026-04-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0046_auto_20260412_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='area_village',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Area (Village)'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='door_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Door No'),
        ),
        migrations.AddField(
            model_name='student',
            name='landline',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='LandLine'),
        ),
        migrations.AddField(
            model_name='student',
            name='mandal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent Email'),
        ),
        migrations.AddField(
            model_name='student',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='PinCode'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
